language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: M5OzLNPqPI87hkttWlR+PNOWlHQdtgjvYNKQdxVXm8g58r1Bo7yueEKyWhYjAXE2eYSRQnzF+u9G1DU7b8NRsPWXAlE/MqYJ2jEfz6YIqJ4cDT2OLSj01OLL+UOzPtwdczjiuCgSFsS0u7MsKzOcGbDOHmouX8zG5RXLJP81ssI=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: lGTiK7GnhlJhw2mwYb2+V7uGqSBHg6bvwaVsyrtvuFwG4h/7gx0v8njwRJ698o88FK9PVCwBVMkdW+w/O09ooMXHKLed11cN4dUUPocZuWXxCLuiC4nQU4fzfJCStESVEHaQcKqZeoFvwz4PZKkbnHy+0vKb5L7rvS+/zKm/lCk=
sudo: false
