language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: mt/iKi1+qAQWdt73Z6d3QkgmliBsKQf+yu4gl9x7zykGipDzh5uXXh8ERgHlD2cLldI028nXHgZ250+pRzJ3JPRCpToa776QR05bGZu3AIHqGv92e1R+Okt+w2CbCEHHkURP/9bIoZRhhFTkvaq//v1gInzzRitezJrnNUb8Uss=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: lGTiK7GnhlJhw2mwYb2+V7uGqSBHg6bvwaVsyrtvuFwG4h/7gx0v8njwRJ698o88FK9PVCwBVMkdW+w/O09ooMXHKLed11cN4dUUPocZuWXxCLuiC4nQU4fzfJCStESVEHaQcKqZeoFvwz4PZKkbnHy+0vKb5L7rvS+/zKm/lCk=
sudo: false
